import type { Player } from './types';

/**
 * Curated roster. To add a player, append an object here — nothing in the
 * simulation code needs to change. Stats are approximate blends across
 * formats, tuned for playful simulation, not scholarship.
 */
export const ROSTER: Player[] = [
  {
    id: 'don-bradman',
    name: 'Don Bradman',
    shortName: 'Bradman',
    country: 'Australia',
    era: { label: '1928–1948', startYear: 1928, endYear: 1948 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, ruthless run machine', bowling: null },
    bio: 'The Don. An average of 99.94 that no one has come within cooee of since.',
    strengths: ['Ruthless consistency', 'Lightning footwork'],
    avatar: { emoji: '🧢', color1: '#0b6623', color2: '#f4c430' },
    batting: { average: 99.94, strikeRate: 58, boundaryPercent: 12.0, sixPercent: 0.2 },
    bowling: null,
  },
  {
    id: 'viv-richards',
    name: 'Viv Richards',
    shortName: 'Viv',
    country: 'West Indies',
    era: { label: '1974–1991', startYear: 1974, endYear: 1991 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, swaggering destroyer', bowling: null },
    bio: 'The Master Blaster. Chewed gum, no helmet, and bowlers for breakfast.',
    strengths: ['Brutal power', 'Fearless hook'],
    avatar: { emoji: '😎', color1: '#7b1e26', color2: '#c69214' },
    batting: { average: 50.23, strikeRate: 85, boundaryPercent: 13.0, sixPercent: 3.0 },
    bowling: null,
  },
  {
    id: 'sachin-tendulkar',
    name: 'Sachin Tendulkar',
    shortName: 'Sachin',
    country: 'India',
    era: { label: '1989–2013', startYear: 1989, endYear: 2013 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, compact and complete', bowling: null },
    bio: 'The Little Master — 100 international centuries and two decades at the top.',
    strengths: ['Straight-drive perfection', 'All-conditions class'],
    avatar: { emoji: '🏏', color1: '#1f4e9c', color2: '#ff9933' },
    batting: { average: 53.78, strikeRate: 68, boundaryPercent: 10.5, sixPercent: 1.0 },
    bowling: null,
  },
  {
    id: 'virat-kohli',
    name: 'Virat Kohli',
    shortName: 'Kohli',
    country: 'India',
    era: { label: '2008–present', startYear: 2008, endYear: null },
    roles: ['batsman'],
    style: { batting: 'Right-hand, chase-master intensity', bowling: null },
    bio: 'King Kohli. Turned run chases into a personal art form.',
    strengths: ['Chase mastery', 'Cover-drive precision'],
    avatar: { emoji: '👑', color1: '#123a75', color2: '#ff9933' },
    batting: { average: 49.3, strikeRate: 74, boundaryPercent: 9.5, sixPercent: 1.4 },
    bowling: null,
  },
  {
    id: 'jacques-kallis',
    name: 'Jacques Kallis',
    shortName: 'Kallis',
    country: 'South Africa',
    era: { label: '1995–2014', startYear: 1995, endYear: 2014 },
    roles: ['batsman', 'bowler'],
    style: {
      batting: 'Right-hand, immovable technician',
      bowling: 'Right-arm fast-medium, canny change-ups',
    },
    bio: 'The great all-rounder: 25,000 international runs and 500+ wickets.',
    strengths: ['Granite defence', 'Canny change-ups'],
    avatar: { emoji: '🪨', color1: '#0f7a3d', color2: '#e8b923' },
    batting: { average: 55.37, strikeRate: 55, boundaryPercent: 8.0, sixPercent: 1.0 },
    bowling: { average: 32.65, economy: 2.83, strikeRate: 69, wicketThreat: 0.6 },
  },
  {
    id: 'dennis-lillee',
    name: 'Dennis Lillee',
    shortName: 'Lillee',
    country: 'Australia',
    era: { label: '1971–1984', startYear: 1971, endYear: 1984 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm fast, aggressive and relentless' },
    bio: 'Moustachioed spearhead of Australia’s 70s pace attack.',
    strengths: ['Raw aggression', 'Relentless accuracy'],
    avatar: { emoji: '🥸', color1: '#0b6623', color2: '#f4c430' },
    batting: null,
    bowling: { average: 23.92, economy: 2.76, strikeRate: 52, wicketThreat: 0.88 },
  },
  {
    id: 'malcolm-marshall',
    name: 'Malcolm Marshall',
    shortName: 'Marshall',
    country: 'West Indies',
    era: { label: '1978–1991', startYear: 1978, endYear: 1991 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm fast, skiddy and lethal' },
    bio: 'Perhaps the most complete fast bowler ever to draw breath.',
    strengths: ['Skiddy pace', 'Lethal bouncer'],
    avatar: { emoji: '⚡', color1: '#7b1e26', color2: '#c69214' },
    batting: null,
    bowling: { average: 20.94, economy: 2.68, strikeRate: 46.7, wicketThreat: 0.95 },
  },
  {
    id: 'shane-warne',
    name: 'Shane Warne',
    shortName: 'Warne',
    country: 'Australia',
    era: { label: '1992–2007', startYear: 1992, endYear: 2007 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Leg-spin, theatre and trickery' },
    bio: 'Bowled the Ball of the Century, then kept topping himself for 15 years.',
    strengths: ['Vicious leg break', 'Mind games'],
    avatar: { emoji: '🌀', color1: '#0b6623', color2: '#f4c430' },
    batting: null,
    bowling: { average: 25.41, economy: 2.65, strikeRate: 57.4, wicketThreat: 0.85 },
  },
  {
    id: 'jasprit-bumrah',
    name: 'Jasprit Bumrah',
    shortName: 'Bumrah',
    country: 'India',
    era: { label: '2016–present', startYear: 2016, endYear: null },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm fast, slingshot yorkers' },
    bio: 'The most unorthodox action in cricket, and the numbers of an all-time great.',
    strengths: ['Toe-crushing yorkers', 'Impossible angles'],
    avatar: { emoji: '🎯', color1: '#1f4e9c', color2: '#ff9933' },
    batting: null,
    bowling: { average: 20.2, economy: 2.75, strikeRate: 42.5, wicketThreat: 0.95 },
  },
];

export const batsmen = () => ROSTER.filter((p) => p.roles.includes('batsman'));
export const bowlers = () => ROSTER.filter((p) => p.roles.includes('bowler'));
