import type { Player } from './types';

/**
 * Curated roster. To add a player, append an object here — nothing in the
 * simulation code needs to change. Stats are approximate blends across
 * formats, tuned for playful simulation, not scholarship.
 */
export const ROSTER: Player[] = [
  {
    id: 'don-bradman',
    name: 'Don Bradman',
    shortName: 'Bradman',
    country: 'Australia',
    era: { label: '1928–1948', startYear: 1928, endYear: 1948 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, ruthless run machine', bowling: null },
    bio: 'The Don. An average of 99.94 that no one has come within cooee of since.',
    strengths: ['Ruthless consistency', 'Lightning footwork'],
    avatar: { emoji: '🧢', color1: '#0b6623', color2: '#f4c430' },
    batting: { average: 99.94, strikeRate: 58, boundaryPercent: 12.0, sixPercent: 0.2 },
    bowling: null,
  },
  {
    id: 'viv-richards',
    name: 'Viv Richards',
    shortName: 'Viv',
    country: 'West Indies',
    era: { label: '1974–1991', startYear: 1974, endYear: 1991 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, swaggering destroyer', bowling: null },
    bio: 'The Master Blaster. Chewed gum, no helmet, and bowlers for breakfast.',
    strengths: ['Brutal power', 'Fearless hook'],
    avatar: { emoji: '😎', color1: '#7b1e26', color2: '#c69214' },
    batting: { average: 50.23, strikeRate: 85, boundaryPercent: 13.0, sixPercent: 3.0 },
    bowling: null,
  },
  {
    id: 'sachin-tendulkar',
    name: 'Sachin Tendulkar',
    shortName: 'Sachin',
    country: 'India',
    era: { label: '1989–2013', startYear: 1989, endYear: 2013 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, compact and complete', bowling: null },
    bio: 'The Little Master — 100 international centuries and two decades at the top.',
    strengths: ['Straight-drive perfection', 'All-conditions class'],
    avatar: { emoji: '🏏', color1: '#1f4e9c', color2: '#ff9933' },
    batting: { average: 53.78, strikeRate: 68, boundaryPercent: 10.5, sixPercent: 1.0 },
    bowling: null,
  },
  {
    id: 'virat-kohli',
    name: 'Virat Kohli',
    shortName: 'Kohli',
    country: 'India',
    era: { label: '2008–present', startYear: 2008, endYear: null },
    roles: ['batsman'],
    style: { batting: 'Right-hand, chase-master intensity', bowling: null },
    bio: 'King Kohli. Turned run chases into a personal art form.',
    strengths: ['Chase mastery', 'Cover-drive precision'],
    avatar: { emoji: '👑', color1: '#123a75', color2: '#ff9933' },
    batting: { average: 49.3, strikeRate: 74, boundaryPercent: 9.5, sixPercent: 1.4 },
    bowling: null,
  },
  {
    id: 'jacques-kallis',
    name: 'Jacques Kallis',
    shortName: 'Kallis',
    country: 'South Africa',
    era: { label: '1995–2014', startYear: 1995, endYear: 2014 },
    roles: ['batsman', 'bowler'],
    style: {
      batting: 'Right-hand, immovable technician',
      bowling: 'Right-arm fast-medium, canny change-ups',
    },
    bio: 'The great all-rounder: 25,000 international runs and 500+ wickets.',
    strengths: ['Granite defence', 'Canny change-ups'],
    avatar: { emoji: '🪨', color1: '#0f7a3d', color2: '#e8b923' },
    batting: { average: 55.37, strikeRate: 55, boundaryPercent: 8.0, sixPercent: 1.0 },
    bowling: { average: 32.65, economy: 2.83, strikeRate: 69, wicketThreat: 0.6 },
  },
  {
    id: 'dennis-lillee',
    name: 'Dennis Lillee',
    shortName: 'Lillee',
    country: 'Australia',
    era: { label: '1971–1984', startYear: 1971, endYear: 1984 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm fast, aggressive and relentless' },
    bio: 'Moustachioed spearhead of Australia’s 70s pace attack.',
    strengths: ['Raw aggression', 'Relentless accuracy'],
    avatar: { emoji: '🥸', color1: '#0b6623', color2: '#f4c430' },
    batting: null,
    bowling: { average: 23.92, economy: 2.76, strikeRate: 52, wicketThreat: 0.88 },
  },
  {
    id: 'malcolm-marshall',
    name: 'Malcolm Marshall',
    shortName: 'Marshall',
    country: 'West Indies',
    era: { label: '1978–1991', startYear: 1978, endYear: 1991 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm fast, skiddy and lethal' },
    bio: 'Perhaps the most complete fast bowler ever to draw breath.',
    strengths: ['Skiddy pace', 'Lethal bouncer'],
    avatar: { emoji: '⚡', color1: '#7b1e26', color2: '#c69214' },
    batting: null,
    bowling: { average: 20.94, economy: 2.68, strikeRate: 46.7, wicketThreat: 0.95 },
  },
  {
    id: 'shane-warne',
    name: 'Shane Warne',
    shortName: 'Warne',
    country: 'Australia',
    era: { label: '1992–2007', startYear: 1992, endYear: 2007 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Leg-spin, theatre and trickery' },
    bio: 'Bowled the Ball of the Century, then kept topping himself for 15 years.',
    strengths: ['Vicious leg break', 'Mind games'],
    avatar: { emoji: '🌀', color1: '#0b6623', color2: '#f4c430' },
    batting: null,
    bowling: { average: 25.41, economy: 2.65, strikeRate: 57.4, wicketThreat: 0.85 },
  },
  {
    id: 'jasprit-bumrah',
    name: 'Jasprit Bumrah',
    shortName: 'Bumrah',
    country: 'India',
    era: { label: '2016–present', startYear: 2016, endYear: null },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm fast, slingshot yorkers' },
    bio: 'The most unorthodox action in cricket, and the numbers of an all-time great.',
    strengths: ['Toe-crushing yorkers', 'Impossible angles'],
    avatar: { emoji: '🎯', color1: '#1f4e9c', color2: '#ff9933' },
    batting: null,
    bowling: { average: 20.2, economy: 2.75, strikeRate: 42.5, wicketThreat: 0.95 },
  },
  {
    id: 'sunil-gavaskar',
    name: 'Sunil Gavaskar',
    shortName: 'Gavaskar',
    country: 'India',
    era: { label: '1971–1987', startYear: 1971, endYear: 1987 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, immaculate opener', bowling: null },
    bio: 'Sunny. Faced the fiercest pace attacks ever assembled without a helmet — and averaged fifty.',
    strengths: ['Impenetrable defence', 'Marathon patience'],
    avatar: { emoji: '🏛️', color1: '#1f4e9c', color2: '#ff9933' },
    batting: { average: 51.12, strikeRate: 55, boundaryPercent: 8.5, sixPercent: 0.3 },
    bowling: null,
  },
  {
    id: 'brian-lara',
    name: 'Brian Lara',
    shortName: 'Lara',
    country: 'West Indies',
    era: { label: '1990–2007', startYear: 1990, endYear: 2007 },
    roles: ['batsman'],
    style: { batting: 'Left-hand, high-backlift flourish', bowling: null },
    bio: 'The Prince. 375, then 400 not out — records that read like typos.',
    strengths: ['Daddy hundreds', 'Wristy flourish'],
    avatar: { emoji: '🖋️', color1: '#7b1e26', color2: '#c69214' },
    batting: { average: 52.89, strikeRate: 76, boundaryPercent: 12.0, sixPercent: 1.3 },
    bowling: null,
  },
  {
    id: 'rahul-dravid',
    name: 'Rahul Dravid',
    shortName: 'Dravid',
    country: 'India',
    era: { label: '1996–2012', startYear: 1996, endYear: 2012 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, the original Wall', bowling: null },
    bio: 'The Wall. Faced 31,258 balls in Tests — more than anyone, ever.',
    strengths: ['The Wall', 'Perfect leave'],
    avatar: { emoji: '🧱', color1: '#1f4e9c', color2: '#ff9933' },
    batting: { average: 52.31, strikeRate: 52, boundaryPercent: 7.5, sixPercent: 0.3 },
    bowling: null,
  },
  {
    id: 'virender-sehwag',
    name: 'Virender Sehwag',
    shortName: 'Sehwag',
    country: 'India',
    era: { label: '1999–2013', startYear: 1999, endYear: 2013 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, see ball hit ball', bowling: null },
    bio: 'Two Test triple-hundreds at a strike rate that made bowlers file complaints.',
    strengths: ['See ball, hit ball', 'Triple-century intent'],
    avatar: { emoji: '🔨', color1: '#1f4e9c', color2: '#ff9933' },
    batting: { average: 45.5, strikeRate: 95, boundaryPercent: 15.0, sixPercent: 2.2 },
    bowling: null,
  },
  {
    id: 'ricky-ponting',
    name: 'Ricky Ponting',
    shortName: 'Ponting',
    country: 'Australia',
    era: { label: '1995–2012', startYear: 1995, endYear: 2012 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, savage puller', bowling: null },
    bio: 'Punter. Three World Cups and a pull shot that belongs in a museum.',
    strengths: ['Savage pull', 'Big-final nerve'],
    avatar: { emoji: '🦘', color1: '#0b6623', color2: '#f4c430' },
    batting: { average: 50.0, strikeRate: 75, boundaryPercent: 11.5, sixPercent: 1.4 },
    bowling: null,
  },
  {
    id: 'adam-gilchrist',
    name: 'Adam Gilchrist',
    shortName: 'Gilchrist',
    country: 'Australia',
    era: { label: '1996–2008', startYear: 1996, endYear: 2008 },
    roles: ['batsman'],
    style: { batting: 'Left-hand, counter-attacking keeper', bowling: null },
    bio: 'Walked when the umpire said not out. Bowlers wished he would walk more often.',
    strengths: ['Counter-attack', 'Walks on principle'],
    avatar: { emoji: '🧤', color1: '#0b6623', color2: '#f4c430' },
    batting: { average: 45.0, strikeRate: 92, boundaryPercent: 13.5, sixPercent: 2.6 },
    bowling: null,
  },
  {
    id: 'ab-de-villiers',
    name: 'AB de Villiers',
    shortName: 'AB',
    country: 'South Africa',
    era: { label: '2004–2018', startYear: 2004, endYear: 2018 },
    roles: ['batsman'],
    style: { batting: 'Right-hand, 360-degree inventor', bowling: null },
    bio: 'Mr 360. Scored to parts of the ground that don’t technically exist.',
    strengths: ['360-degree scoring', 'Impossible improvisation'],
    avatar: { emoji: '🧭', color1: '#0f7a3d', color2: '#e8b923' },
    batting: { average: 50.66, strikeRate: 90, boundaryPercent: 12.5, sixPercent: 2.5 },
    bowling: null,
  },
  {
    id: 'kapil-dev',
    name: 'Kapil Dev',
    shortName: 'Kapil',
    country: 'India',
    era: { label: '1978–1994', startYear: 1978, endYear: 1994 },
    roles: ['batsman', 'bowler'],
    style: {
      batting: 'Right-hand, fearless hitter',
      bowling: 'Right-arm fast-medium, outswing artist',
    },
    bio: 'The Haryana Hurricane — 1983, that catch, that hundred, that cup.',
    strengths: ['Outswing at pace', 'Fearless hitting'],
    avatar: { emoji: '🌪️', color1: '#1f4e9c', color2: '#ff9933' },
    batting: { average: 31.05, strikeRate: 88, boundaryPercent: 11.0, sixPercent: 2.0 },
    bowling: { average: 29.65, economy: 3.1, strikeRate: 70, wicketThreat: 0.65 },
  },
  {
    id: 'imran-khan',
    name: 'Imran Khan',
    shortName: 'Imran',
    country: 'Pakistan',
    era: { label: '1971–1992', startYear: 1971, endYear: 1992 },
    roles: ['batsman', 'bowler'],
    style: {
      batting: 'Right-hand, captain’s temperament',
      bowling: 'Right-arm fast, reverse-swing pioneer',
    },
    bio: 'Cornered tigers, 1992, and one of the great fast-bowling all-rounders.',
    strengths: ['Reverse-swing pioneer', 'Captain’s steel'],
    avatar: { emoji: '🐅', color1: '#01411c', color2: '#d4af37' },
    batting: { average: 37.69, strikeRate: 65, boundaryPercent: 8.0, sixPercent: 1.2 },
    bowling: { average: 22.81, economy: 2.9, strikeRate: 53, wicketThreat: 0.85 },
  },
  {
    id: 'garry-sobers',
    name: 'Garry Sobers',
    shortName: 'Sobers',
    country: 'West Indies',
    era: { label: '1954–1974', startYear: 1954, endYear: 1974 },
    roles: ['batsman', 'bowler'],
    style: {
      batting: 'Left-hand, effortless genius',
      bowling: 'Left-arm anything — pace or spin',
    },
    bio: 'Six sixes in an over, 8,032 Test runs, and three bowlers in one body.',
    strengths: ['Six sixes', 'Three bowlers in one'],
    avatar: { emoji: '🌟', color1: '#7b1e26', color2: '#c69214' },
    batting: { average: 57.78, strikeRate: 62, boundaryPercent: 10.5, sixPercent: 1.6 },
    bowling: { average: 34.04, economy: 2.9, strikeRate: 92, wicketThreat: 0.5 },
  },
  {
    id: 'wasim-akram',
    name: 'Wasim Akram',
    shortName: 'Wasim',
    country: 'Pakistan',
    era: { label: '1984–2003', startYear: 1984, endYear: 2003 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Left-arm fast, two-way swing' },
    bio: 'The Sultan of Swing. Made an old ball more dangerous than a new one.',
    strengths: ['Two-way swing', 'Yorker from nowhere'],
    avatar: { emoji: '🪃', color1: '#01411c', color2: '#d4af37' },
    batting: null,
    bowling: { average: 23.62, economy: 3.0, strikeRate: 49, wicketThreat: 0.9 },
  },
  {
    id: 'glenn-mcgrath',
    name: 'Glenn McGrath',
    shortName: 'McGrath',
    country: 'Australia',
    era: { label: '1993–2007', startYear: 1993, endYear: 2007 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm fast-medium, metronome' },
    bio: 'Pigeon. Bowled the same unplayable ball for fourteen years.',
    strengths: ['Metronomic line', 'Top-of-off obsession'],
    avatar: { emoji: '📏', color1: '#0b6623', color2: '#f4c430' },
    batting: null,
    bowling: { average: 21.64, economy: 2.5, strikeRate: 52, wicketThreat: 0.85 },
  },
  {
    id: 'muttiah-muralitharan',
    name: 'Muttiah Muralitharan',
    shortName: 'Murali',
    country: 'Sri Lanka',
    era: { label: '1992–2011', startYear: 1992, endYear: 2011 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm off spin, big-turning doosra' },
    bio: '800 Test wickets. The most prolific bowler who ever gripped a ball.',
    strengths: ['Big-turning doosra', 'Marathon spells'],
    avatar: { emoji: '🔮', color1: '#8d153a', color2: '#eb7400' },
    batting: null,
    bowling: { average: 22.73, economy: 2.6, strikeRate: 55, wicketThreat: 0.9 },
  },
  {
    id: 'anil-kumble',
    name: 'Anil Kumble',
    shortName: 'Kumble',
    country: 'India',
    era: { label: '1990–2008', startYear: 1990, endYear: 2008 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm leg spin, bounce over turn' },
    bio: 'Jumbo. All ten in an innings — and once bowled with a broken jaw.',
    strengths: ['Ten-for tenacity', 'Bounce and fizz'],
    avatar: { emoji: '🐘', color1: '#1f4e9c', color2: '#ff9933' },
    batting: null,
    bowling: { average: 30.0, economy: 2.8, strikeRate: 63, wicketThreat: 0.7 },
  },
  {
    id: 'curtly-ambrose',
    name: 'Curtly Ambrose',
    shortName: 'Ambrose',
    country: 'West Indies',
    era: { label: '1988–2000', startYear: 1988, endYear: 2000 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm fast, steepling bounce' },
    bio: 'Six foot seven of bad news. Once took seven for one in a single spell.',
    strengths: ['Steepling bounce', 'Miserly menace'],
    avatar: { emoji: '🗼', color1: '#7b1e26', color2: '#c69214' },
    batting: null,
    bowling: { average: 20.99, economy: 2.3, strikeRate: 54, wicketThreat: 0.9 },
  },
  {
    id: 'dale-steyn',
    name: 'Dale Steyn',
    shortName: 'Steyn',
    country: 'South Africa',
    era: { label: '2004–2019', startYear: 2004, endYear: 2019 },
    roles: ['bowler'],
    style: { batting: null, bowling: 'Right-arm fast, late outswing' },
    bio: 'The best strike rate of the modern age, delivered at a snarl.',
    strengths: ['Late outswing', 'Raw hostility'],
    avatar: { emoji: '💨', color1: '#0f7a3d', color2: '#e8b923' },
    batting: null,
    bowling: { average: 22.95, economy: 3.2, strikeRate: 42, wicketThreat: 0.92 },
  },
];

export const batsmen = () => ROSTER.filter((p) => p.roles.includes('batsman'));
export const bowlers = () => ROSTER.filter((p) => p.roles.includes('bowler'));
